<?php  //[STAMP] 5671c798fcafe50bc0c8061bfd0746d4
namespace techPump\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait \techPump\FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
